#!/usr/bin/python
#
# Copyright 2016 Ernst-Georg Schmid
#
#ISC License
#
#Copyright (c) 2017, Ernst-Georg Schmid
#
#Permission to use, copy, modify, and/or distribute this software for any
#purpose with or without fee is hereby granted, provided that the above
#copyright notice and this permission notice appear in all copies.
#
#THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
#REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
#AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
#INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
#LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
#OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
#PERFORMANCE OF THIS SOFTWARE.

# -*- coding: utf-8 -*-
"""
@author: ergo
"""

import sys
from mhash import HMAC, MHASH_RIPEMD128
from os import urandom, path, chmod
from socket import getfqdn

CONFIG = path.expanduser("~") + '/.skey'

if(len(sys.argv) == 2):
    size = int(sys.argv[1])
else:
    size = 10;

if(size > 50):
    size = 50;

c = 1
base = 48

hashes = []

iv = urandom(16).encode('hex')
p = urandom(16).encode('hex')

next_hash = HMAC(MHASH_RIPEMD128, p, iv).hexdigest()

for n in xrange(1, 999999):
    next_hash = HMAC(MHASH_RIPEMD128, p, next_hash).hexdigest()

for i in xrange(0, size):
    sys.stderr.write('#')
    hashes.append('-'.join(next_hash[i:i+4] for i in xrange(0, len(next_hash), 4)))
    for n in xrange(1, 1000000):
        next_hash = HMAC(MHASH_RIPEMD128, p, next_hash).hexdigest()

try:   
    chmod(CONFIG, 0200)
except:
    pass 
   
with open(CONFIG, 'w') as last_seen:
    last_seen.write(chr(base + size))
    last_seen.write(p)
    last_seen.write(next_hash)
    
chmod(CONFIG, 0400)    

hashes.reverse()

sys.stderr.write('\n')

print(getfqdn()+'\n')    
    
for i in hashes:
    print str(c) +'\t' + i
    c+=1
